# Generated by Django 4.1.4 on 2023-01-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='')),
                ('cuerpo', models.CharField(max_length=500)),
                ('nombreAutor', models.CharField(max_length=50)),
                ('apellidoAutor', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
            ],
        ),
    ]
