# Generated by Django 4.1.4 on 2023-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
        migrations.AddField(
            model_name='perfil',
            name='intereses',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ocupacion',
            field=models.CharField(max_length=50),
        ),
    ]
