# Generated by Django 4.1.4 on 2023-01-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_perfil_apellido_remove_perfil_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='username',
            new_name='user',
        ),
    ]
