# Generated by Django 4.1.4 on 2023-01-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
