# Generated by Django 4.1.4 on 2023-01-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_alter_posteos_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posteos'),
        ),
    ]
