# Generated by Django 4.1.4 on 2023-01-20 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajesApp', '0003_alter_mensajes_emisor_alter_mensajes_receptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='emisor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
